name: Run test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: foo
    steps:
    - name: test echo
      run: |
       echo "test pull request"
